[
    {
        "id": 2,
        "chargingStationIdentity": "Borne005",
        "status": "Available",
        "info": null,
        "errorCode": "NoError",
        "vendorId": null,
        "vendorErrorCode": null,
        "wiring": "1",
        "freeValue": 16,
        "standard": "IEC61851",
        "type": "TE",
        "sheddingType": null,
        "equipmentId": null,
        "limit": null,
        "maxPoint": 16,
        "createdAt": "2024-07-03T14:19:30.000000Z",
        "updatedAt": "2025-10-03T08:25:02.000000Z"
    },
    {
        "id": 3,
        "chargingStationIdentity": "Borne005",
        "status": "Available",
        "info": null,
        "errorCode": "NoError",
        "vendorId": null,
        "vendorErrorCode": null,
        "wiring": "123",
        "freeValue": 32,
        "standard": "IEC61851",
        "type": "T2",
        "sheddingType": {
            "type": "SetChargingProfile",
            "args": {
                "purpose": "TxProfile",
                "chargingProfileId": 3,
                "stackLevel": 0,
                "numberPhases": false,
                "chargingRateUnit": "A"
            }
        },
        "equipmentId": null,
        "limit": null,
        "maxPoint": 32,
        "createdAt": "2024-07-03T14:19:30.000000Z",
        "updatedAt": "2025-05-06T01:10:01.000000Z"
    },
    {
        "id": 1,
        "chargingStationIdentity": "Borne005",
        "status": "Available",
        "info": null,
        "errorCode": "NoError",
        "vendorId": null,
        "vendorErrorCode": null,
        "wiring": "123",
        "freeValue": 32,
        "standard": "IEC61851",
        "type": "T2",
        "sheddingType": {
            "type": "SetChargingProfile",
            "args": {
                "purpose": "TxProfile",
                "chargingProfileId": 1,
                "stackLevel": 0,
                "numberPhases": false,
                "chargingRateUnit": "A"
            }
        },
        "equipmentId": null,
        "limit": 12,
        "maxPoint": 32,
        "createdAt": "2024-07-03T14:19:30.000000Z",
        "updatedAt": "2025-10-31T10:02:29.000000Z"
    },
    {
        "id": 4,
        "chargingStationIdentity": "Borne004",
        "status": "Available",
        "info": null,
        "errorCode": "NoError",
        "vendorId": null,
        "vendorErrorCode": null,
        "wiring": "1",
        "freeValue": 16,
        "standard": "IEC61851",
        "type": "TE",
        "sheddingType": null,
        "equipmentId": null,
        "limit": null,
        "maxPoint": 16,
        "createdAt": "2024-07-03T14:19:19.000000Z",
        "updatedAt": "2025-05-06T01:10:01.000000Z"
    },
    {
        "id": 3,
        "chargingStationIdentity": "Borne004",
        "status": "Available",
        "info": null,
        "errorCode": "NoError",
        "vendorId": null,
        "vendorErrorCode": null,
        "wiring": "123",
        "freeValue": 32,
        "standard": "IEC61851",
        "type": "T2",
        "sheddingType": {
            "type": "SetChargingProfile",
            "args": {
                "purpose": "TxProfile",
                "chargingProfileId": 3,
                "stackLevel": 0,
                "numberPhases": false,
                "chargingRateUnit": "A"
            }
        },
        "equipmentId": null,
        "limit": null,
        "maxPoint": 32,
        "createdAt": "2024-07-03T14:19:19.000000Z",
        "updatedAt": "2025-10-09T13:54:09.000000Z"
    },
    {
        "id": 2,
        "chargingStationIdentity": "Borne004",
        "status": "Available",
        "info": null,
        "errorCode": "NoError",
        "vendorId": null,
        "vendorErrorCode": null,
        "wiring": "1",
        "freeValue": 16,
        "standard": "IEC61851",
        "type": "TE",
        "sheddingType": null,
        "equipmentId": null,
        "limit": null,
        "maxPoint": 16,
        "createdAt": "2024-07-03T14:19:19.000000Z",
        "updatedAt": "2025-05-06T01:10:01.000000Z"
    },
    {
        "id": 4,
        "chargingStationIdentity": "Borne003",
        "status": "Available",
        "info": null,
        "errorCode": "NoError",
        "vendorId": null,
        "vendorErrorCode": null,
        "wiring": "1",
        "freeValue": 16,
        "standard": "IEC61851",
        "type": "TE",
        "sheddingType": null,
        "equipmentId": null,
        "limit": null,
        "maxPoint": 16,
        "createdAt": "2024-07-03T14:19:08.000000Z",
        "updatedAt": "2025-05-06T01:10:01.000000Z"
    },
    {
        "id": 1,
        "chargingStationIdentity": "Borne004",
        "status": "Available",
        "info": null,
        "errorCode": "NoError",
        "vendorId": null,
        "vendorErrorCode": null,
        "wiring": "123",
        "freeValue": 32,
        "standard": "IEC61851",
        "type": "T2",
        "sheddingType": {
            "type": "SetChargingProfile",
            "args": {
                "purpose": "TxProfile",
                "chargingProfileId": 1,
                "stackLevel": 0,
                "numberPhases": false,
                "chargingRateUnit": "A"
            }
        },
        "equipmentId": null,
        "limit": null,
        "maxPoint": 32,
        "createdAt": "2024-07-03T14:19:19.000000Z",
        "updatedAt": "2025-07-18T14:40:33.000000Z"
    },
    {
        "id": 2,
        "chargingStationIdentity": "Borne003",
        "status": "Available",
        "info": null,
        "errorCode": "NoError",
        "vendorId": null,
        "vendorErrorCode": null,
        "wiring": "1",
        "freeValue": 16,
        "standard": "IEC61851",
        "type": "TE",
        "sheddingType": null,
        "equipmentId": null,
        "limit": null,
        "maxPoint": 16,
        "createdAt": "2024-07-03T14:19:08.000000Z",
        "updatedAt": "2025-05-06T01:10:01.000000Z"
    },
    {
        "id": 3,
        "chargingStationIdentity": "Borne003",
        "status": "Available",
        "info": null,
        "errorCode": "NoError",
        "vendorId": null,
        "vendorErrorCode": null,
        "wiring": "123",
        "freeValue": 32,
        "standard": "IEC61851",
        "type": "T2",
        "sheddingType": {
            "type": "SetChargingProfile",
            "args": {
                "purpose": "TxProfile",
                "chargingProfileId": 3,
                "stackLevel": 0,
                "numberPhases": false,
                "chargingRateUnit": "A"
            }
        },
        "equipmentId": null,
        "limit": null,
        "maxPoint": 32,
        "createdAt": "2024-07-03T14:19:08.000000Z",
        "updatedAt": "2025-05-06T01:10:01.000000Z"
    },
    {
        "id": 1,
        "chargingStationIdentity": "Borne003",
        "status": "Available",
        "info": null,
        "errorCode": "NoError",
        "vendorId": null,
        "vendorErrorCode": null,
        "wiring": "123",
        "freeValue": 32,
        "standard": "IEC61851",
        "type": "T2",
        "sheddingType": {
            "type": "SetChargingProfile",
            "args": {
                "purpose": "TxProfile",
                "chargingProfileId": 1,
                "stackLevel": 0,
                "numberPhases": false,
                "chargingRateUnit": "A"
            }
        },
        "equipmentId": null,
        "limit": 16,
        "maxPoint": 32,
        "createdAt": "2024-07-03T14:19:08.000000Z",
        "updatedAt": "2025-05-06T01:10:01.000000Z"
    },
    {
        "id": 3,
        "chargingStationIdentity": "Borne002",
        "status": "Available",
        "info": null,
        "errorCode": "NoError",
        "vendorId": null,
        "vendorErrorCode": null,
        "wiring": "123",
        "freeValue": 32,
        "standard": "IEC61851",
        "type": "T2",
        "sheddingType": {
            "type": "SetChargingProfile",
            "args": {
                "purpose": "TxProfile",
                "chargingProfileId": 3,
                "stackLevel": 0,
                "numberPhases": false,
                "chargingRateUnit": "A"
            }
        },
        "equipmentId": null,
        "limit": null,
        "maxPoint": 32,
        "createdAt": "2024-07-03T14:18:51.000000Z",
        "updatedAt": "2025-10-15T11:38:57.000000Z"
    },
    {
        "id": 4,
        "chargingStationIdentity": "Borne002",
        "status": "Available",
        "info": null,
        "errorCode": "NoError",
        "vendorId": null,
        "vendorErrorCode": null,
        "wiring": "1",
        "freeValue": 16,
        "standard": "IEC61851",
        "type": "TE",
        "sheddingType": null,
        "equipmentId": null,
        "limit": null,
        "maxPoint": 16,
        "createdAt": "2024-07-03T14:18:51.000000Z",
        "updatedAt": "2025-05-06T01:10:01.000000Z"
    },
    {
        "id": 2,
        "chargingStationIdentity": "Borne002",
        "status": "Available",
        "info": null,
        "errorCode": "NoError",
        "vendorId": null,
        "vendorErrorCode": null,
        "wiring": "1",
        "freeValue": 16,
        "standard": "IEC61851",
        "type": "TE",
        "sheddingType": null,
        "equipmentId": null,
        "limit": null,
        "maxPoint": 16,
        "createdAt": "2024-07-03T14:18:51.000000Z",
        "updatedAt": "2025-05-06T01:10:01.000000Z"
    },
    {
        "id": 1,
        "chargingStationIdentity": "Borne002",
        "status": "Available",
        "info": null,
        "errorCode": "NoError",
        "vendorId": null,
        "vendorErrorCode": null,
        "wiring": "123",
        "freeValue": 32,
        "standard": "IEC61851",
        "type": "T2",
        "sheddingType": {
            "type": "SetChargingProfile",
            "args": {
                "purpose": "TxProfile",
                "chargingProfileId": 1,
                "stackLevel": 0,
                "numberPhases": false,
                "chargingRateUnit": "A"
            }
        },
        "equipmentId": null,
        "limit": null,
        "maxPoint": 32,
        "createdAt": "2024-07-03T14:18:51.000000Z",
        "updatedAt": "2025-10-15T11:38:58.000000Z"
    },
    {
        "id": 2,
        "chargingStationIdentity": "Borne001",
        "status": "Available",
        "info": null,
        "errorCode": "NoError",
        "vendorId": null,
        "vendorErrorCode": null,
        "wiring": "123",
        "freeValue": 16,
        "standard": "IEC61851",
        "type": "TE",
        "sheddingType": null,
        "equipmentId": null,
        "limit": null,
        "maxPoint": 16,
        "createdAt": "2024-07-03T14:15:58.000000Z",
        "updatedAt": "2025-10-31T10:02:29.000000Z"
    },
    {
        "id": 1,
        "chargingStationIdentity": "Borne001",
        "status": "Available",
        "info": null,
        "errorCode": "NoError",
        "vendorId": null,
        "vendorErrorCode": null,
        "wiring": "123",
        "freeValue": 32,
        "standard": "IEC61851",
        "type": "T2",
        "sheddingType": {
            "type": "SetChargingProfile",
            "args": {
                "purpose": "TxProfile",
                "chargingProfileId": 1,
                "stackLevel": 0,
                "numberPhases": false,
                "chargingRateUnit": "A"
            }
        },
        "equipmentId": null,
        "limit": null,
        "maxPoint": 32,
        "createdAt": "2024-07-03T14:15:58.000000Z",
        "updatedAt": "2025-11-25T09:16:44.000000Z"
    },
    {
        "id": 4,
        "chargingStationIdentity": "Borne005",
        "status": "Available",
        "info": null,
        "errorCode": "NoError",
        "vendorId": null,
        "vendorErrorCode": null,
        "wiring": "1",
        "freeValue": 16,
        "standard": "IEC61851",
        "type": "TE",
        "sheddingType": null,
        "equipmentId": null,
        "limit": null,
        "maxPoint": 16,
        "createdAt": "2024-07-03T14:19:30.000000Z",
        "updatedAt": "2025-05-06T01:10:01.000000Z"
    },
    {
        "id": 1,
        "chargingStationIdentity": "Borne006",
        "status": "Available",
        "info": null,
        "errorCode": "NoError",
        "vendorId": null,
        "vendorErrorCode": null,
        "wiring": "123",
        "freeValue": 32,
        "standard": "IEC61851",
        "type": "T2",
        "sheddingType": {
            "type": "SetChargingProfile",
            "args": {
                "purpose": "TxProfile",
                "chargingProfileId": 1,
                "stackLevel": 0,
                "numberPhases": false,
                "chargingRateUnit": "A"
            }
        },
        "equipmentId": null,
        "limit": null,
        "maxPoint": 32,
        "createdAt": "2024-07-03T14:20:43.000000Z",
        "updatedAt": "2025-05-06T01:10:01.000000Z"
    },
    {
        "id": 2,
        "chargingStationIdentity": "Borne006",
        "status": "Available",
        "info": null,
        "errorCode": "NoError",
        "vendorId": null,
        "vendorErrorCode": null,
        "wiring": "1",
        "freeValue": 16,
        "standard": "IEC61851",
        "type": "TE",
        "sheddingType": null,
        "equipmentId": null,
        "limit": null,
        "maxPoint": 16,
        "createdAt": "2024-07-03T14:20:43.000000Z",
        "updatedAt": "2025-05-06T01:10:01.000000Z"
    },
    {
        "id": 3,
        "chargingStationIdentity": "Borne006",
        "status": "Available",
        "info": null,
        "errorCode": "NoError",
        "vendorId": null,
        "vendorErrorCode": null,
        "wiring": "123",
        "freeValue": 32,
        "standard": "IEC61851",
        "type": "T2",
        "sheddingType": {
            "type": "SetChargingProfile",
            "args": {
                "purpose": "TxProfile",
                "chargingProfileId": 3,
                "stackLevel": 0,
                "numberPhases": false,
                "chargingRateUnit": "A"
            }
        },
        "equipmentId": null,
        "limit": null,
        "maxPoint": 32,
        "createdAt": "2024-07-03T14:20:43.000000Z",
        "updatedAt": "2025-05-06T01:10:01.000000Z"
    },
    {
        "id": 4,
        "chargingStationIdentity": "Borne006",
        "status": "Available",
        "info": null,
        "errorCode": "NoError",
        "vendorId": null,
        "vendorErrorCode": null,
        "wiring": "1",
        "freeValue": 16,
        "standard": "IEC61851",
        "type": "TE",
        "sheddingType": null,
        "equipmentId": null,
        "limit": null,
        "maxPoint": 16,
        "createdAt": "2024-07-03T14:20:43.000000Z",
        "updatedAt": "2025-05-06T01:10:01.000000Z"
    },
    {
        "id": 1,
        "chargingStationIdentity": "Borne007",
        "status": "Available",
        "info": null,
        "errorCode": "NoError",
        "vendorId": null,
        "vendorErrorCode": null,
        "wiring": "123",
        "freeValue": 32,
        "standard": "IEC61851",
        "type": "T2",
        "sheddingType": {
            "type": "SetChargingProfile",
            "args": {
                "purpose": "TxProfile",
                "chargingProfileId": 1,
                "stackLevel": 0,
                "numberPhases": false,
                "chargingRateUnit": "A"
            }
        },
        "equipmentId": null,
        "limit": 20,
        "maxPoint": 32,
        "createdAt": "2024-07-03T14:22:20.000000Z",
        "updatedAt": "2025-05-06T01:10:01.000000Z"
    },
    {
        "id": 2,
        "chargingStationIdentity": "Borne007",
        "status": "Available",
        "info": null,
        "errorCode": "NoError",
        "vendorId": null,
        "vendorErrorCode": null,
        "wiring": "1",
        "freeValue": 16,
        "standard": "IEC61851",
        "type": "TE",
        "sheddingType": null,
        "equipmentId": null,
        "limit": null,
        "maxPoint": 16,
        "createdAt": "2024-07-03T14:22:20.000000Z",
        "updatedAt": "2025-05-06T01:10:01.000000Z"
    },
    {
        "id": 3,
        "chargingStationIdentity": "Borne007",
        "status": "Available",
        "info": null,
        "errorCode": "NoError",
        "vendorId": null,
        "vendorErrorCode": null,
        "wiring": "123",
        "freeValue": 32,
        "standard": "IEC61851",
        "type": "T2",
        "sheddingType": {
            "type": "SetChargingProfile",
            "args": {
                "purpose": "TxProfile",
                "chargingProfileId": 3,
                "stackLevel": 0,
                "numberPhases": false,
                "chargingRateUnit": "A"
            }
        },
        "equipmentId": null,
        "limit": null,
        "maxPoint": 32,
        "createdAt": "2024-07-03T14:22:20.000000Z",
        "updatedAt": "2025-05-06T01:10:01.000000Z"
    },
    {
        "id": 4,
        "chargingStationIdentity": "Borne007",
        "status": "Available",
        "info": null,
        "errorCode": "NoError",
        "vendorId": null,
        "vendorErrorCode": null,
        "wiring": "1",
        "freeValue": 16,
        "standard": "IEC61851",
        "type": "TE",
        "sheddingType": null,
        "equipmentId": null,
        "limit": null,
        "maxPoint": 16,
        "createdAt": "2024-07-03T14:22:20.000000Z",
        "updatedAt": "2025-05-06T01:10:01.000000Z"
    },
    {
        "id": 1,
        "chargingStationIdentity": "Borne008",
        "status": "Available",
        "info": null,
        "errorCode": "NoError",
        "vendorId": null,
        "vendorErrorCode": null,
        "wiring": "123",
        "freeValue": 32,
        "standard": "IEC61851",
        "type": "T2",
        "sheddingType": {
            "type": "SetChargingProfile",
            "args": {
                "purpose": "TxProfile",
                "chargingProfileId": 1,
                "stackLevel": 0,
                "numberPhases": false,
                "chargingRateUnit": "A"
            }
        },
        "equipmentId": null,
        "limit": null,
        "maxPoint": 32,
        "createdAt": "2024-07-03T14:22:36.000000Z",
        "updatedAt": "2025-05-06T01:10:01.000000Z"
    },
    {
        "id": 2,
        "chargingStationIdentity": "Borne008",
        "status": "Available",
        "info": null,
        "errorCode": "NoError",
        "vendorId": null,
        "vendorErrorCode": null,
        "wiring": "1",
        "freeValue": 16,
        "standard": "IEC61851",
        "type": "TE",
        "sheddingType": null,
        "equipmentId": null,
        "limit": null,
        "maxPoint": 16,
        "createdAt": "2024-07-03T14:22:36.000000Z",
        "updatedAt": "2025-05-06T01:10:01.000000Z"
    },
    {
        "id": 3,
        "chargingStationIdentity": "Borne008",
        "status": "Available",
        "info": null,
        "errorCode": "NoError",
        "vendorId": null,
        "vendorErrorCode": null,
        "wiring": "123",
        "freeValue": 32,
        "standard": "IEC61851",
        "type": "T2",
        "sheddingType": {
            "type": "SetChargingProfile",
            "args": {
                "purpose": "TxProfile",
                "chargingProfileId": 3,
                "stackLevel": 0,
                "numberPhases": false,
                "chargingRateUnit": "A"
            }
        },
        "equipmentId": null,
        "limit": null,
        "maxPoint": 32,
        "createdAt": "2024-07-03T14:22:36.000000Z",
        "updatedAt": "2025-05-06T01:10:01.000000Z"
    },
    {
        "id": 4,
        "chargingStationIdentity": "Borne008",
        "status": "Available",
        "info": null,
        "errorCode": "NoError",
        "vendorId": null,
        "vendorErrorCode": null,
        "wiring": "1",
        "freeValue": 16,
        "standard": "IEC61851",
        "type": "TE",
        "sheddingType": null,
        "equipmentId": null,
        "limit": null,
        "maxPoint": 16,
        "createdAt": "2024-07-03T14:22:36.000000Z",
        "updatedAt": "2025-05-06T01:10:01.000000Z"
    },
    {
        "id": 1,
        "chargingStationIdentity": "Borne009",
        "status": "Available",
        "info": null,
        "errorCode": "NoError",
        "vendorId": null,
        "vendorErrorCode": null,
        "wiring": "123",
        "freeValue": 32,
        "standard": "IEC61851",
        "type": "T2",
        "sheddingType": {
            "type": "SetChargingProfile",
            "args": {
                "purpose": "TxProfile",
                "chargingProfileId": 1,
                "stackLevel": 0,
                "numberPhases": false,
                "chargingRateUnit": "A"
            }
        },
        "equipmentId": null,
        "limit": null,
        "maxPoint": 32,
        "createdAt": "2024-07-03T14:22:45.000000Z",
        "updatedAt": "2025-05-06T01:10:01.000000Z"
    },
    {
        "id": 2,
        "chargingStationIdentity": "Borne009",
        "status": "Available",
        "info": null,
        "errorCode": "NoError",
        "vendorId": null,
        "vendorErrorCode": null,
        "wiring": "1",
        "freeValue": 16,
        "standard": "IEC61851",
        "type": "TE",
        "sheddingType": null,
        "equipmentId": null,
        "limit": null,
        "maxPoint": 16,
        "createdAt": "2024-07-03T14:22:45.000000Z",
        "updatedAt": "2025-05-06T01:10:01.000000Z"
    },
    {
        "id": 3,
        "chargingStationIdentity": "Borne009",
        "status": "Available",
        "info": null,
        "errorCode": "NoError",
        "vendorId": null,
        "vendorErrorCode": null,
        "wiring": "123",
        "freeValue": 32,
        "standard": "IEC61851",
        "type": "T2",
        "sheddingType": {
            "type": "SetChargingProfile",
            "args": {
                "purpose": "TxProfile",
                "chargingProfileId": 3,
                "stackLevel": 0,
                "numberPhases": false,
                "chargingRateUnit": "A"
            }
        },
        "equipmentId": null,
        "limit": null,
        "maxPoint": 32,
        "createdAt": "2024-07-03T14:22:45.000000Z",
        "updatedAt": "2025-05-06T01:10:01.000000Z"
    },
    {
        "id": 4,
        "chargingStationIdentity": "Borne009",
        "status": "Available",
        "info": null,
        "errorCode": "NoError",
        "vendorId": null,
        "vendorErrorCode": null,
        "wiring": "1",
        "freeValue": 16,
        "standard": "IEC61851",
        "type": "TE",
        "sheddingType": null,
        "equipmentId": null,
        "limit": null,
        "maxPoint": 16,
        "createdAt": "2024-07-03T14:22:45.000000Z",
        "updatedAt": "2025-05-06T01:10:01.000000Z"
    },
    {
        "id": 1,
        "chargingStationIdentity": "Borne010",
        "status": "Available",
        "info": null,
        "errorCode": "NoError",
        "vendorId": null,
        "vendorErrorCode": null,
        "wiring": "2",
        "freeValue": 32,
        "standard": "IEC61851",
        "type": "T2",
        "sheddingType": {
            "type": "SetChargingProfile",
            "args": {
                "purpose": "TxProfile",
                "chargingProfileId": 1,
                "stackLevel": 0,
                "numberPhases": false,
                "chargingRateUnit": "A"
            }
        },
        "equipmentId": null,
        "limit": null,
        "maxPoint": 32,
        "createdAt": "2024-07-03T14:22:56.000000Z",
        "updatedAt": "2025-07-23T09:56:57.000000Z"
    },
    {
        "id": 2,
        "chargingStationIdentity": "Borne010",
        "status": "Available",
        "info": null,
        "errorCode": "NoError",
        "vendorId": null,
        "vendorErrorCode": null,
        "wiring": "1",
        "freeValue": 16,
        "standard": "IEC61851",
        "type": "TE",
        "sheddingType": null,
        "equipmentId": null,
        "limit": null,
        "maxPoint": 16,
        "createdAt": "2024-07-03T14:22:56.000000Z",
        "updatedAt": "2025-05-06T01:10:01.000000Z"
    },
    {
        "id": 3,
        "chargingStationIdentity": "Borne010",
        "status": "Available",
        "info": null,
        "errorCode": "NoError",
        "vendorId": null,
        "vendorErrorCode": null,
        "wiring": "3",
        "freeValue": 32,
        "standard": "IEC61851",
        "type": "T2",
        "sheddingType": {
            "type": "SetChargingProfile",
            "args": {
                "purpose": "TxProfile",
                "chargingProfileId": 3,
                "stackLevel": 0,
                "numberPhases": false,
                "chargingRateUnit": "A"
            }
        },
        "equipmentId": null,
        "limit": null,
        "maxPoint": 32,
        "createdAt": "2024-07-03T14:22:56.000000Z",
        "updatedAt": "2025-05-06T01:10:01.000000Z"
    },
    {
        "id": 4,
        "chargingStationIdentity": "Borne010",
        "status": "Available",
        "info": null,
        "errorCode": "NoError",
        "vendorId": null,
        "vendorErrorCode": null,
        "wiring": "1",
        "freeValue": 16,
        "standard": "IEC61851",
        "type": "TE",
        "sheddingType": null,
        "equipmentId": null,
        "limit": null,
        "maxPoint": 16,
        "createdAt": "2024-07-03T14:22:56.000000Z",
        "updatedAt": "2025-05-06T01:10:01.000000Z"
    },
    {
        "id": 3,
        "chargingStationIdentity": "Borne001",
        "status": "Available",
        "info": null,
        "errorCode": "NoError",
        "vendorId": null,
        "vendorErrorCode": null,
        "wiring": "123",
        "freeValue": 12,
        "standard": "IEC61851",
        "type": "T2",
        "sheddingType": {
            "type": "SetChargingProfile",
            "args": {
                "purpose": "TxProfile",
                "chargingProfileId": 3,
                "stackLevel": 0,
                "numberPhases": true,
                "chargingRateUnit": "A"
            }
        },
        "equipmentId": null,
        "limit": 0,
        "maxPoint": 0,
        "createdAt": "2024-09-19T08:28:25.000000Z",
        "updatedAt": "2025-11-04T16:04:55.000000Z"
    },
    {
        "id": 4,
        "chargingStationIdentity": "Borne001",
        "status": "Available",
        "info": null,
        "errorCode": "NoError",
        "vendorId": null,
        "vendorErrorCode": null,
        "wiring": "123",
        "freeValue": 32,
        "standard": "IEC61851",
        "type": "T2",
        "sheddingType": null,
        "equipmentId": null,
        "limit": null,
        "maxPoint": 32,
        "createdAt": "2025-03-25T11:14:51.000000Z",
        "updatedAt": "2025-10-31T10:02:29.000000Z"
    },
    {
        "id": 1,
        "chargingStationIdentity": "LP9DCH2",
        "status": "Available",
        "info": null,
        "errorCode": "NoError",
        "vendorId": null,
        "vendorErrorCode": null,
        "wiring": "123",
        "freeValue": 32,
        "standard": "IEC61851",
        "type": "T2",
        "sheddingType": {
            "type": "SetChargingProfile",
            "args": {
                "purpose": "TxProfile",
                "chargingProfileId": 1,
                "stackLevel": 0,
                "numberPhases": false,
                "chargingRateUnit": "A"
            }
        },
        "equipmentId": null,
        "limit": null,
        "maxPoint": 32,
        "createdAt": "2025-07-18T13:27:51.000000Z",
        "updatedAt": "2025-11-10T17:21:07.000000Z"
    },
    {
        "id": 2,
        "chargingStationIdentity": "LP9DCH2",
        "status": "Available",
        "info": null,
        "errorCode": "NoError",
        "vendorId": null,
        "vendorErrorCode": null,
        "wiring": "123",
        "freeValue": 32,
        "standard": "IEC61851",
        "type": "T2",
        "sheddingType": {
            "type": "SetChargingProfile",
            "args": {
                "purpose": "TxProfile",
                "chargingProfileId": 1,
                "stackLevel": 0,
                "numberPhases": false,
                "chargingRateUnit": "A"
            }
        },
        "equipmentId": null,
        "limit": null,
        "maxPoint": 32,
        "createdAt": "2025-07-18T13:27:51.000000Z",
        "updatedAt": "2025-11-10T17:21:07.000000Z"
    },
    {
        "id": 3,
        "chargingStationIdentity": "LP9DCH2",
        "status": "Available",
        "info": null,
        "errorCode": "NoError",
        "vendorId": null,
        "vendorErrorCode": null,
        "wiring": "123",
        "freeValue": 32,
        "standard": "IEC61851",
        "type": "T2",
        "sheddingType": {
            "type": "SetChargingProfile",
            "args": {
                "purpose": "TxProfile",
                "chargingProfileId": 1,
                "stackLevel": 0,
                "numberPhases": false,
                "chargingRateUnit": "A"
            }
        },
        "equipmentId": null,
        "limit": null,
        "maxPoint": 32,
        "createdAt": "2025-07-18T13:27:51.000000Z",
        "updatedAt": "2025-11-14T10:47:33.000000Z"
    },
    {
        "id": 4,
        "chargingStationIdentity": "LP9DCH2",
        "status": "Available",
        "info": null,
        "errorCode": "NoError",
        "vendorId": null,
        "vendorErrorCode": null,
        "wiring": "123",
        "freeValue": 32,
        "standard": "IEC61851",
        "type": "T2",
        "sheddingType": {
            "type": "SetChargingProfile",
            "args": {
                "purpose": "TxProfile",
                "chargingProfileId": 1,
                "stackLevel": 0,
                "numberPhases": false,
                "chargingRateUnit": "A"
            }
        },
        "equipmentId": null,
        "limit": null,
        "maxPoint": 32,
        "createdAt": "2025-07-18T13:27:51.000000Z",
        "updatedAt": "2025-11-14T10:47:43.000000Z"
    },
    {
        "id": 1,
        "chargingStationIdentity": "EVB-P1949856",
        "status": "Unavailable",
        "info": null,
        "errorCode": "NoError",
        "vendorId": null,
        "vendorErrorCode": null,
        "wiring": "123",
        "freeValue": 32,
        "standard": "IEC61851",
        "type": "T2",
        "sheddingType": null,
        "equipmentId": null,
        "limit": null,
        "maxPoint": null,
        "createdAt": "2025-11-06T17:03:00.000000Z",
        "updatedAt": "2025-11-13T05:28:31.000000Z"
    },
    {
        "id": 2,
        "chargingStationIdentity": "EVB-P1949856",
        "status": "Unavailable",
        "info": null,
        "errorCode": "NoError",
        "vendorId": null,
        "vendorErrorCode": null,
        "wiring": "123",
        "freeValue": 32,
        "standard": "IEC61851",
        "type": "T2",
        "sheddingType": null,
        "equipmentId": null,
        "limit": null,
        "maxPoint": null,
        "createdAt": "2025-11-06T17:03:00.000000Z",
        "updatedAt": "2025-11-13T05:28:29.000000Z"
    },
    {
        "id": 1,
        "chargingStationIdentity": "EVB-P2008143",
        "status": "Unavailable",
        "info": null,
        "errorCode": "NoError",
        "vendorId": null,
        "vendorErrorCode": null,
        "wiring": "123",
        "freeValue": 32,
        "standard": "IEC61851",
        "type": "T2",
        "sheddingType": null,
        "equipmentId": null,
        "limit": null,
        "maxPoint": null,
        "createdAt": "2025-11-06T17:22:28.000000Z",
        "updatedAt": "2025-11-13T05:28:17.000000Z"
    },
    {
        "id": 2,
        "chargingStationIdentity": "EVB-P2008143",
        "status": null,
        "info": null,
        "errorCode": null,
        "vendorId": null,
        "vendorErrorCode": null,
        "wiring": "123",
        "freeValue": 32,
        "standard": "IEC61851",
        "type": "T2",
        "sheddingType": null,
        "equipmentId": null,
        "limit": null,
        "maxPoint": null,
        "createdAt": "2025-11-06T17:22:28.000000Z",
        "updatedAt": "2025-11-06T17:22:28.000000Z"
    },
    {
        "id": 1,
        "chargingStationIdentity": "EVB-P1941308",
        "status": "Unavailable",
        "info": null,
        "errorCode": "NoError",
        "vendorId": null,
        "vendorErrorCode": null,
        "wiring": "123",
        "freeValue": 32,
        "standard": "IEC61851",
        "type": "T2",
        "sheddingType": null,
        "equipmentId": null,
        "limit": null,
        "maxPoint": null,
        "createdAt": "2025-11-13T05:25:08.000000Z",
        "updatedAt": "2025-11-13T05:29:39.000000Z"
    },
    {
        "id": 2,
        "chargingStationIdentity": "EVB-P1941308",
        "status": "Unavailable",
        "info": null,
        "errorCode": "NoError",
        "vendorId": null,
        "vendorErrorCode": null,
        "wiring": "123",
        "freeValue": 32,
        "standard": "IEC61851",
        "type": "T2",
        "sheddingType": null,
        "equipmentId": null,
        "limit": null,
        "maxPoint": null,
        "createdAt": "2025-11-13T05:25:08.000000Z",
        "updatedAt": "2025-11-13T05:29:39.000000Z"
    },
    {
        "id": 4,
        "chargingStationIdentity": "LEG-MAGRE8",
        "status": "Faulted",
        "info": "Error.power.outage",
        "errorCode": "UnderVoltage",
        "vendorId": null,
        "vendorErrorCode": "0012",
        "wiring": "1",
        "freeValue": 16,
        "standard": "IEC61851",
        "type": "TE",
        "sheddingType": null,
        "equipmentId": null,
        "limit": null,
        "maxPoint": null,
        "createdAt": "2025-11-24T14:33:42.000000Z",
        "updatedAt": "2025-11-24T15:17:06.000000Z"
    },
    {
        "id": 2,
        "chargingStationIdentity": "LEG-MAGRE8",
        "status": "Available",
        "info": null,
        "errorCode": "NoError",
        "vendorId": null,
        "vendorErrorCode": null,
        "wiring": "1",
        "freeValue": 16,
        "standard": "IEC61851",
        "type": "TE",
        "sheddingType": null,
        "equipmentId": null,
        "limit": null,
        "maxPoint": null,
        "createdAt": "2025-11-24T14:33:42.000000Z",
        "updatedAt": "2025-11-24T14:35:19.000000Z"
    },
    {
        "id": 1,
        "chargingStationIdentity": "LEG-MAGRE8",
        "status": "Available",
        "info": null,
        "errorCode": "NoError",
        "vendorId": null,
        "vendorErrorCode": null,
        "wiring": "123",
        "freeValue": 32,
        "standard": "IEC61851",
        "type": "T2",
        "sheddingType": {
            "type": "SetChargingProfile",
            "args": {
                "purpose": "TxProfile",
                "chargingProfileId": 1,
                "stackLevel": 0,
                "numberPhases": false,
                "chargingRateUnit": "A"
            }
        },
        "equipmentId": null,
        "limit": null,
        "maxPoint": null,
        "createdAt": "2025-11-24T14:33:42.000000Z",
        "updatedAt": "2025-11-24T14:35:19.000000Z"
    },
    {
        "id": 3,
        "chargingStationIdentity": "LEG-MAGRE8",
        "status": "Faulted",
        "info": "Error.power.outage",
        "errorCode": "UnderVoltage",
        "vendorId": null,
        "vendorErrorCode": "0012",
        "wiring": "123",
        "freeValue": 32,
        "standard": "IEC61851",
        "type": "T2",
        "sheddingType": {
            "type": "SetChargingProfile",
            "args": {
                "purpose": "TxProfile",
                "chargingProfileId": 1,
                "stackLevel": 0,
                "numberPhases": false,
                "chargingRateUnit": "A"
            }
        },
        "equipmentId": null,
        "limit": null,
        "maxPoint": null,
        "createdAt": "2025-11-24T14:33:42.000000Z",
        "updatedAt": "2025-11-24T15:17:06.000000Z"
    }
]

export interface ISheddingType {
  type: string;
  args: {
    purpose: string;
    chargingProfileId: number;
    stackLevel: number;
    numberPhases: boolean;
    chargingRateUnit: string;
  };
}

export interface ICSConnector {
  id: number;
  chargingStationIdentity: string;
  status: string | null;
  info: string | null;
  errorCode: string | null;
  vendorId: string | null;
  vendorErrorCode: string | null;
  wiring: string;
  freeValue: number;
  standard: string;
  type: string;
  sheddingType: ISheddingType | null;
  equipmentId: number | null;
  limit: number | null;
  maxPoint: number | null;
  createdAt: string;
  updatedAt: string;
}